sample1:
	g++ sample1.cc -I/usr/include/log4cpp -llog4cpp -lpthread

sample2:
	g++ sample2.cc -I/usr/include/log4cpp -llog4cpp -lpthread

sample3:
	g++ sample3.cc -I/usr/include/log4cpp -llog4cpp -lpthread

clean:
	rm -f a.out *.log
