simple_get:
	g++ -lcurl -I/usr/include/curl simple_get.cc

simple_post:
	g++ -lcurl -I/usr/include/curl simple_post.cc

multi_get:
	g++ -lcurl -I/usr/include/curl multi_get.cc

multi_post:
	g++ -lcurl -I/usr/include/curl multi_post.cc
