epoll1:
	gcc -o epoll1 epoll1.c

epoll2:
	gcc -o epoll2 epoll2.c

epoll3:
	gcc -o epoll3 epoll3.c

epoll4:
	gcc -o epoll4 epoll4.c

epoll5:
	gcc -o epoll5 epoll5.c

clean:
	rm -f a.out epoll1 epoll2 epoll3 epoll4 epoll5
