upcast1: InputStream.h  Stream.h
	g++ InputStream.cpp  Stream.cpp  Upcast1.cpp

upcast1_2: InputStream.h  Stream.h
	g++ InputStream.cpp  Stream.cpp  Upcast1_2.cpp

upcast2: ArrayStream.h InputStream.h  Stream.h
	g++ ArrayStream.cpp InputStream.cpp  Stream.cpp  Upcast2.cpp

clean:
	rm -f ./a.out
