compare_exchange_weak:
	g++ -std=c++11 -pthread compare_exchange_weak.cc -o compare_exchange_weak

atomic_class_template:
	g++ -std=c++11 -pthread atomic_class_template.cc -o atomic_class_template

memory_order_acquire.release:
	g++ -std=c++11 -pthread memory_order_acquire.release.cc -o memory_order_acquire.release

clean:
	rm -f a.out
