helloworld:
	g++ helloworld.cpp -lyaml-cpp

write_sample1:
	g++ write_sample1.cpp -lyaml-cpp

read_sample1:
	g++ read_sample1.cpp -lyaml-cpp

read_sample2:
	g++ read_sample2.cpp -lyaml-cpp

clean:
	rm -f ./a.out

