xpath1:
	g++ -lxml2 -I/usr/include/libxml2 xpath_sample1.cc

xpath2:
	g++ -lxml2 -I/usr/include/libxml2 xpath_sample2.cc

treewalk1:
	g++ -lxml2 -I/usr/include/libxml2 treewalk1.cc

rssparse:
	g++ -lxml2 -I/usr/include/libxml2 rssparse.cc

test:
	g++ -lxml2 -I/usr/include/libxml2 test.cc

clean:
	rm ./a.out
