all:
	gcc -o server_recvfrom server_recvfrom.c
	gcc -o server_recvmsg server_recvmsg.c
	gcc -o client_sendto client_sendto.c
	gcc -o client_sendmsg client_sendmsg.c

clean:
	rm -f client_sendmsg client_sendto server_recvfrom server_recvmsg
